name: protex
description: "A TeX editor and precompiler that integrates Python and LaTeX."
publish_to: 'none'
version: 0.1.0+UMS

environment:
  sdk: ^3.7.0

dependencies:
  cross_file: ^0.3.4+2
  desktop_drop: ^0.5.0
  file_picker: ^9.2.0
  filesystem_picker: ^4.1.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pubspec_parse: ^1.5.0
  shared_preferences: ^2.5.2
  smooth_animated_listview: ^0.0.2
  super_clipboard: ^0.9.1
  system_theme: ^3.1.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  window_manager: ^0.4.3
  html_to_tex:
    path: /home/abloom/Nextcloud/Documents/htmlToTeX/html_to_tex

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - pubspec.yaml
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-VariableFont_wght.ttf
        - asset: fonts/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic