name: protex
version: '0.1.0'
summary: A TeX editor and precompiler that integrates Python and LaTeX.
description: |
  Protex is a TeX editor and precompiler that integrates Python and LaTeX.
  It provides a user-friendly interface for editing multiple TeX documents and compiling them with embedded Python scripts.
  Protex is designed to simplify the process of creating and managing TeX documents, making it easier for users to work with LaTeX and Python together. It allows for documents that can change with every compile to include updated data from Python scripts, making it a powerful tool for generating dynamic reports and documents.
  It is particularly useful for researchers, students, and professionals who frequently work with TeX documents and need a reliable tool for editing and compiling them.

base: core22
confinement: devmode
grade: stable

apps:
  protex:
    command: protex
    extensions: [gnome]

parts:
  protex:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart